### ISSUE TITLE
Haddocks didn't built on Hackage

### ISSUE THREAD

**Issue by mitchellwrosen** [schernichkin/partial-isomorphisms#5]
https://hackage.haskell.org/package/partial-isomorphisms

**Comment by schernichkin** [comment]
Hackage attempts to use GHC 8.10 to build package, however partial-isomorphisms-0.2.3 requires GHC 9.0. I do not know how to make Hackage to use particular version of GHC. I've submitted a version with updated constraint `base >= 4.15` and uploaded haddocks manually https://hackage.haskell.org/package/partial-isomorphisms-0.2.3.1/candidate 

If it's OK, I'll publish this candate. Otherwise give me a hint how can I fix it in a proper way.

**Comment by mitchellwrosen** [comment]
Oh, sure thing! You can create docs locally with something like `cabal haddock all --haddock-for-hackage --haddock-hyperlink-source --haddock-quickjump`, then upload with `cabal publish -d <the-docs-tarball> --publish`

**Comment by mitchellwrosen** [comment]
Sorry, I misread your question. I see that you already know how to upload docs manually.

Uploading a new version seems fine, but if it's just a bounds tweak, you could also publish a revision (either via the command line using `hackage-cli`, or by clicking around in the Hackage UI). This would avoid appending a whole new source tarball to the Hackage index.
